language: python

python:
    - 3.6

install: 
    - pip install requirements

before_script:
    - python manage.py makemigrations snuariapi
    - python manage.py migrate

script:
    - python manage.py test
